microsoft/D3D12TranslationLayer

include/RootSignature.hpp, include/Shader.hpp, src/CommandListManager.cpp, src/ImmediateContext.cpp, src/PipelineState.cpp, src/Shader.cpp, src/ShaderParser.cpp, src/VideoDecode.cpp, src/VideoDecodeStatistics.cpp, src/VideoReferenceDataManager.cpp
- Add Shader creation method for non-owning non-parsing creation, to enable non-owning DXIL shaders.
- Add null checks for tracelogging handle to prevent crashes if tracelogging is unused.
=> Update interface for shader creation, fix tracelogging assumptions

include/Allocator.h, include/BlockAllocators.h
This is deprecated in C++17 and removed in C++20.
=> std::result_of -> std::invoke_result to avoid deprecation

src/ImmediateContext.cpp
Only emit heavy descriptor heap usage event when using ring buffer descriptor heaps.
=> Remove noisy tracelogging event

include/ResourceCache.hpp, src/ImmediateContext.cpp, src/ResourceCache.cpp
ClearResourceWithNoRenderTarget always attempted to use the resource format for the RTV format for formats that could support render target.  This doesn't work for AYUV which must use a supported video view:
https://docs.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format
This modifies that code path to use DXGI_FORMAT_R8G8B8A8_UINT for the view format.
=> D3D11On12: Clearing an AYUV View Using Incorrect RTV Format

include/ImmediateContext.inl
MSVC outputs a spurious warning here while compiling ApplyAllResourceTransitions.
=> Add warning suppression to GetCommandListManager

include/Allocator.h, include/BatchedContext.hpp, include/ImmediateContext.hpp, include/Util.hpp, src/BatchedContext.cpp
Destruction in D3D11 can be free-threaded. Currently the batched context appends all destructions to the end the current batch. That means that an immediate context operation (most likely an explicit flush) is needed before those resources are moved to the next level of deferral in the immediate context. That means that an app is likelier to run out of memory if it has large resources caught up waiting for this flush.
This change adds a lock to work recording, which has has contention against creation (initial data upload) and enqueueing of destruction. That allows the work batches to be flushed by any application thread. Batches are explicitly sent to the worker thread if they contain destruction of "large" (arbitrarily determined) resources.
=> Synchronization changes to enable D3D11On12 earlier release of memory

include/BatchedContext.hpp, include/BatchedQuery.hpp, src/BatchedContext.cpp
There's two things here:
1. The check for worker thread idle in SyncWithBatch is wrong.
2. The use of the batch reference can miss cases where Begin/End are inside a command list.
The first commit is a straightforward fix for the race condition in problem 1.
The second commit is a complex reworking of how references to batches are managed to address problem 2.
=> Fixes for async query GetData checking

CMakeLists.txt, include/D3D12TranslationLayerIncludes.h, src/CMakeLists.txt
Rather than hardcoding in the header, this allows them to be turned off.
=> Add on-by-default CMake option to use PIX for release builds

include/View.hpp, include/View.inl, src/View.cpp
This can end up racing with ops like RotateResourceIdentities, potentially snapping the wrong view uniqueness/resource pairing.
=> Don't initialize descriptors during view creation

include/ImmediateContext.hpp, src/ImmediateContext.cpp, src/Resource.cpp
Adds plumbing and logic so that deferred destruction also checks deferred waits.  This fixes an issue where work externally scheduled through unwrap/return underlying resources was not waited for during deferred destruction
=> Wait for deferred waits during deferred destruction

include/ResourceBinding.hpp, include/View.hpp, src/BlitHelper.cpp, src/ImmediateContext.cpp, src/VideoProcess.cpp
Otherwise we can end up using uninitialized descriptors if it was assumed that view construction initialized the descriptor.
=> Make sure view descriptors are refreshed whenever the descriptor is accessed for binding

include/Resource.hpp, include/d3dx12Residency.h, src/Resource.cpp
This change adds support to residency management for pinning a resource.  Pinning prevents resources from being evicted by trim activities when under memory pressure.  Used initially by UnwrapUnderlyingResource to prevent application checked out resources from being evicted while in use by the caller.
=> Add residency pinning for UnwrapUnderlyingResource

include/ImmediateContext.hpp, src/BlitHelper.cpp
Some hardware handles this incorrectly.
=> Add flag which causes blits from YUY2 to use [0,0.5] coords instead of [0,1]

include/BatchedContext.hpp
This helps keep them from sticking around too long, which can cause problems in some cases.
=> Also force batch flushing for destruction of shared resources

src/ResourceState.cpp
Wait for the last write state transition for a resource when transitioning to a shared read state.
Prior to this change, only the next transition to a shared read state would wait for the write to complete. In the repro, a resource is used in an exclusive write state for decode output. Then the resource was used as a reference in a subsequent decode and as input to a video process operation. If the decode came first, it would transition to a shared read state and wait for the write to complete, but the subsequent video process operation would not.
=> Wait for the last write state transition for a resource when transitioning to a shared read state.

src/ImmediateContext.cpp
This keeps them from sticking around if we're not submitting graphics work.
=> Use a decode command list type for decode-allocated rename resources

include/ResourceState.hpp, src/ResourceState.cpp
Keep track of which cross-queue synchronization has been done so we don't re-do it over and over. Also don't try to synchronize a queue to itself.
=> Don't re-insert the same synchronization over and over

include/CommandListManager.hpp, src/ResourceState.cpp
-SharedFenceSignal was called for non-shared fences. SharedFenceSignal use is deprecated, so remove entirely. 
-ShouldFlushForResourceAcquire only checked draws and dispatches which could lead to deadlocks with UnwrapUnderlyingResource.
=> SharedFenceSignal use removed.  ShouldFlushForResourceAcquire check for more than dispatches/draws

include/ImmediateContext.hpp, src/BatchedContext.cpp, src/ImmediateContext.cpp
D3D9On12 has a scenario where it needs to upload CPU data straight in the B10G10R10A2 format (`D3DFMT_A2R10G10B10`) into a D3D12 R10G10B10A2 texture, since D3D12 doesn't have a format for the channel-swapped variant. Normally, D3D9On12 uses shader techniques to do the channel swap, but this scenario doesn't have the data in a GPU-visible format already before the swap needs to happen.
=> Add support for uploading B10G10R10A2 data to an R10G10B10A2 texture

src/Resource.cpp
Underlying device removed results in an uncaught exception through UnwrapUnderlyingResource
=> Catch _com_error and convert to HRESULT in AddFenceForUnwrapResidency

src/Resource.cpp
D3D12 validates that cross-adapter textures can't use any compatibility flags
=> Don't use the 9on12 compatibility flag when creating cross-adapter textures

src/ImmediateContext.cpp
Descriptor Heap roll over telemetry is too noisy.
=> Remove noisy telemetry

src/VideoDecode.cpp
Set H264 max slices in VideoDecode::GetVideoDecoderBufferInfo based on codec spec
=> Set H264 max slices in VideoDecode::GetVideoDecoderBufferInfo based on codec spec

include/VideoReferenceDataManager.hpp, src/VideoDecode.cpp, src/VideoReferenceDataManager.cpp
There was an issue with some MPEG2 and VC1 videos that have the following pattern:
1) Decode a couple frames and add them to DPB for usage as reference pictures in future frames
2) Decode a frame that doesn't use reference frames. **At this point the DPB is emptied by the translation layer.**
3) Decode a frame that used references from frames decoded in step (1) and emptied in step (2). At this point ReferenceDataManager::UpdateEntry issues "Decode - Invalid Reference Index" and remaps it to the current
// picture index to avoid crashing and still attempt to decode.
This pull request changes the DPB eviction strategy for MPEG2 and VC1, by keeping alive the reference pictures from previous frames when the current frame doesn't use any reference pictures, but still evicts as before when the …
=> [Video Decode] Change reference pictures DPB eviction policy for codecs MPEG2 and VC1

include/BlitHelper.hpp, src/BlitHelper.cpp
BlitHelper doesn't support blitting MSAA textures, so now we will check
if the source was an MSAA texture and then resolve it to a non msaa
texture if needed before performing the blit.
=> Blit helper now resolves msaa resource to non msaa

CMakeLists.txt, include/D3D12TranslationLayerDependencyIncludes.h, include/D3D12TranslationLayerIncludes.h, include/ImmediateContext.hpp, include/XPlatHelpers.h, src/CMakeLists.txt, src/CommandListManager.cpp, src/ImmediateContext.cpp
This change makes this project use DirectX-Headers for D3D12 and DXCore headers instead of relying on getting them from the SDK. That does 2 things:
1. Means we can compile-time depend on new APIs being available - obviously runtime still needs to potentially handle them not being there.
2. Means this library no longer depends on an insider SDK, since the DXCore headers are now included, and the library is made optional.
=> Switch to using DirectX-Headers

include/D3D12TranslationLayerDependencyIncludes.h
This simplifies header dependencies. Rather than pulling in all the Windows.h bloat, we can just pull in the main stuff and wincrypt.h for its NTSTATUS definition.
=> Use Win32 lean and mean (+wincrypt.h)

include/BlitHelper.hpp, src/BlitHelper.cpp
D3D12's ResolveSubresource expects the destination dimensions
to be as large or larger than the source (taking into account msaa
scaling). The apps we were testing with happened to call blit with a
source Rect of matching dimensions, so when we created our intermediate
resource in ResolveToNonMsaa we had the appropriate size. This doesn't
work when the app only blits a section of the source resource though. In
this case our intermediate resource ends up being too small and the
resolve fails. The solution is to create an intermediate resource of the
same size as the source resource's underlying d3d12 resource.
=> Fix BlitHelper::ResolveToNonMsaa

include/Resource.hpp, src/BatchedContext.cpp, src/ImmediateContext.cpp
This was originally written with D3D11 in mind, which will block recursive maps, but D3D9 (and older) will let them through. This fixes a bug with double-unmap attempting to access a null pRenameResource.
Also fix the calls to actually map the heaps to use subresource index instead of plane index.
=> Use per-plane map refcounts instead of just a bitmask

src/ImmediateContext.cpp
Missed these when skimming the previous change, since the code structure changed, the intra-line change wasn't highlighted as obviously.
=> Revert additional PlaneIndex => Subresource changes

CMakeLists.txt, src/CMakeLists.txt
The DXBC parser and builder components should only be included when the WDK is found, since they depend on it.
=> CMake: Fix WDK dependency

include/CommandListManager.hpp, include/ImmediateContext.hpp, src/CommandListManager.cpp, src/ImmediateContext.cpp, src/Resource.cpp, src/VideoDecode.cpp
Add ability to provide MaxAllocatedUploadSpacePerCommandList via ImmediateContext creation args.
Add ability to provide MaxSRVHeapSize via ImmediateContext creation args.
Fix compiler warnings found with VS 2022.
=> Allow setting of MaxAllocatedUploadSpacePerCommandList

src/ImmediateContext.cpp
Fixes a regression from a74474d1d9a7d358768b202ab2bd2198b7f023b6 when used with D3D11On12/OpenCLOn12 which don't set this arg (clearing the struct to 0s).
=> When max SRV heap size is 0 from upper layer args, use a reasonable default

README.md
DXCore Insider SDK version is no longer required to build.
=> Remove mention of DXCore Insider SDK requirement from readme.

include/ImmediateContext.hpp, include/ImmediateContext.inl, src/ImmediateContext.cpp, src/Query.cpp, src/VideoDecode.cpp, src/VideoProcess.cpp
Fix for cases where exceptions are "escaping" a stack trace with a no-except method in between when calling SubmitCommandList
For example:
void VideoDecode::DecodeFrame
is calling
inline void ImmediateContext::SubmitCommandList(COMMAND_LIST_TYPE commandListType) **noexcept**
and this delegates to (different namespace, same fn name)
void CommandListManager::SubmitCommandList()
...
throw in CloseCommandList(...)
Removed noexcept from SubmitCommandList and WaitForFenceValue.
Adapted noexcept callers of this functions to convert the possible exceptions to appropiate return values
=> Removed noexcept from SubmitCommandList and WaitForFenceValue

include/d3dx12Residency.h
GetCurrentBudget for LM and Non-LM is taking up a lot of CPU-time in the residency management logic, but it can be moved into a conditional branch for "Count > 1" (num cmd lists) which is frequently skipped.
Expecting ~1% performance gain on CS:GO for some platforms
=> Move GetCurrentBudget calls into conditional to save performance

src/ImmediateContext.cpp
Otherwise setting `-DUSE_PIX=OFF` on the CMake command line can cause unreferenced parameter warnings/errors.
=> Tag PIX functions as maybe_unused

include/CommandListManager.hpp, include/ImmediateContext.hpp, src/CommandListManager.cpp
CommandListManager/ImmediateContext: Create CBoundedFencePool to allow for CPU blocking after N in-flight pending commands. Apply 16 limit to Video Decode cmdlists.
Fixes https://github.com/microsoft/D3D11On12/issues/40
=> CommandListManager/ImmediateContext: Limit in-flight Video Decode operations to 16 and wait on CPU when pool is full

CMakeLists.txt, include/ImmediateContext.hpp, src/ImmediateContext.cpp
When supported by the D3D12 version we're using, we can create a sync-only queue, which can only have signals and waits on it and is lighter weight than any other queue type. On this queue, we can do waits for all of our internal fences to complete, followed by a signal for the caller's fence, which effectively allows us to broadcast the signal to only complete when all internal timelines reach the appropriate completion point.
=> Use a synchronization-only command queue (COMMAND_LIST_TYPE_NONE) for Signal()

src/ImmediateContext.cpp
Resolving a depth+stencil format resource isn't valid due to the stencil
UINT component, so we should only resolve the depth plane and also tell d3d
that the stencil plane is typeless. 
(In particular this was causing a crash in Star Wars: The Old Republic with high AA settings)
D16_UNORM isn't supported for resolving either, so just pretend that it's
R16_UNORM.
=> Fix bug with resolving MSAA depth+stencil resources

src/Residency.cpp
Equal was wrong, a > check was needed. Otherwise, the WaitForCommandList tries to re-flush the command list that we're in the middle of flushing.
=> Fix conditions for determining when we have to stop trying to wait for the GPU to evict more memory

src/ImmediateContext.cpp
Avoids a warning about depth being enabled but no depth buffer being bound.
=> Disable depth for GenerateMips

include/ImmediateContext.inl, include/ResourceBinding.hpp
The Apply*Helper()s didn't verify that the shader they were trying to bind resources to actually used that type of resource, so there were cases where we would try to bind invalid data to shaders that didn't reference it. This didn't cause issues in applications, but does log a breaking error in the debug layer.
=> Check shader decls before binding SRV, CB, samplers

include/BatchedContext.hpp
We've (the compiler team) started enforcing that `{}` initialization can't do narrowing conversions in more places, which means that this code will be broken in a new version of the compiler; this is one method to fix this; the alternative is to compare with `0` in the initialization of a few structure members down-file.
Note that this _does not_ break ABI, due to the following pointer member.
old:
```
class D3D12TranslationLayer::BatchedContext::CreationArgs       size(16):
+---
0.     | CreatesAndDestroysAreMultithreaded (bitstart=0,nbits=1)
0.     | SubmitBatchesToWorkerThread (bitstart=1,nbits=1)
| <alignment member> (size=4)
8      | pParentContext
+---
```
new:
```
class D3D12TranslationLayer::BatchedContext::CreationArgs       size(16):
+---
0.     | …
```
=> Fix narrowing conversion in `{}`

include/Shader.inl
SetConstantBuffers() was previously setting the dirty flag unconditionally, even when the states aren't actually dirty, which likely caused PreDraw() to do lots of unnecessary work.
However, it still needs to set the flag if the offset to the buffer changes or if the number of constants change. If the buffer itself changes, UpdateBinding() will set the dirty flag.
I've tested the change on an RTX 3070 with a map in CS:GO, and the FPS increased by about around 35%.
=> Fix Dirty Flag Issue in SetConstantBuffers

include/ImmediateContext.hpp, src/BatchedContext.cpp, src/ImmediateContext.cpp
I'm not entirely sure how this could happen, but I did see a hang occur due to a loop where an app was polling a query status, and we were trying to wait for a fence value that wasn't associated with a command list (i.e. no actual commands were recorded) but the fence hadn't been signaled yet, so the wait was never satisfied. I suppose an event query is has no commands associated with it, so this could happen there.
=> Ensure pending signals are submitted when async polling query status

include/D3D12TranslationLayerDependencyIncludes.h, include/ImmediateContext.inl
This fixes a build break that will happen when the STL from VS 17.8 reaches windows.
=> stop using the internal _Ty type of std::bitset

include/Residency.h
This is in line with how we make other calls to min and max in the translation layer.
=> Remove std:: prefix from std::min call

include/ImmediateContext.inl, include/Util.hpp, src/Residency.cpp, src/ResourceState.cpp, src/SharedResourceHelpers.cpp, src/VideoDevice.cpp, src/VideoReferenceDataManager.cpp
Generally tried to just change counting variables to size_t to match the comparison.
In cases where the counting variable was assigned in to other narrower types I just did an assert on the size of the comparison value and then static_cast it to match.
Realistically shouldn't hit these situations anyway.
=> [TSA bugs] Fix narrow/wide type comparison in loop condition

src/Resource.cpp
When 9on12 doesn't translate lockable shared buffers to `HEAP_TYPE_DEFAULT` (i.e. UMA), we go down the wrong path, and map/unmap doesn't actually get contents into the shared buffer anymore. This is a simple fix to redirect that.
=> Fix lockable shared buffers

src/Residency.cpp, src/Resource.cpp
The case in Resource.cpp shouldn't ever be able to cause the infinite loop that CodeQL is concerned about since we are removing entries from the list (the size there is the source of the wider type)
=> [TSA] fix Comparison of narrow type with wide type in loop condition

src/VideoProcess.cpp
This is similar to the pattern in ~VideoDecode to handle failures in flushing the commandlist in a destructor.
=> Swallow failures in ~VideoProcess()

include/BlockAllocators.h, include/DeviceChild.hpp, include/ImmediateContext.hpp, include/ImmediateContext.inl, include/ResourceBinding.hpp, include/View.hpp, include/View.inl, include/segmented_stack.h, src/BlitHelper.cpp, src/DeviceChild.cpp, src/ImmediateContext.cpp, src/Resource.cpp, src/SubresourceHelpers.cpp, src/VideoDecodeStatistics.cpp, src/VideoProcess.cpp
This PR fixes compilation of D3D12TranslationLayer under `/permissive-` and C++20. It expands upon the conformance fixes from https://github.com/microsoft/D3D12TranslationLayer/pull/28 but does not attempt to resolve the circular dependency issue (this may be worth considering for a followup PR.)
=> Fix compilation under /permissive- and C++20

src/CommandListManager.cpp
A new D3D12 warning will fire when calling `SetEventOnCompletion` for fence value 0, which is always completed. Let's not do that.
=> Don't call SetEventOnCompletion for an already-completed fence value
